### ISSUE TITLE
2e interaction: laat de link omhoog en omlaag gaan na een hover (Event: mouseover)

### ISSUE THREAD

**Issue by Karima002** [Karima002/UI-events#3]
### ANALYSEREN

Bron: https://www.kirupa.com/html5/mouse_events_in_javascript.html
https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseover_event

**Comment by Karima002** [comment]
### ONTWERPEN
![image](https://github.com/user-attachments/assets/69158b81-4aad-413f-a81d-a39b9537a092)

**Comment by Karima002** [comment]
### Integreren

Na het bouwen is de code gepusht in de volgende commit:

Commit: 68e8b3a

**Comment by Karima002** [comment]
### TESTEN
@itsValyria zou je mijn interactie kunnen testen?

**Comment by itsValyria** [comment]
Hey Karima!

Ik heb gekeken naar deze interactie, die jij vast hebt gemaakt aan de `Design` button op jouw UI events web page.

Wat mij opviel is dat de animatie niet helemaal vloeiend loopt, en ik denk dat dit komt doordat hij niet begint en eindigt bij een nul punt (0px). Ook eindigt de keyframe niet bij 100%. 

Voorbeeld nu: 

```css
@keyframes upping {
  0% {
    transform: translateY(20px);
  }
  30% {
    transform: translateY(0px);
  }
  50% {
    transform: translateY(-20px);
  }
  60% {
    transform: translateY(0px);
  }
  70% {
    transform: translateY(20px);
  }
}
```

Voorbeeld hoe ik het zou doen:
> Wat vooral belangrijk is, is dat je start en eind positie hetzelfde is als hoe het element normaal staat, zo krijg je een zo smooth mogelijke animatie.

```css
@keyframes upping {
  0% {
    transform: translateY(0px);
  }
  25% {
    transform: translateY(20px);
  }
  50% {
    transform: translateY(-20px);
  }
  75% {
    transform: translateY(20px);
  }
  100% {
    transform: translateY(0px);
  }
}
```

Hier kun je nog wat andere [best practices](https://blog.pixelfreestudio.com/how-to-create-smooth-css-animations-best-practices/) lezen voor smooth CSS animations. :)

<img src="https://media0.giphy.com/media/l41YmQjOz9qg2Ecow/giphy.gif"/>
